function ChatButtonClick(callingScreen){var chatUrl="/chat/chatform.aspx";if(callingScreen==="Password Questions"){chatUrl+="?team=TAA_SVE_MFA Chat";}else{if(getSearchInputObject().val()!==""){chatUrl=chatUrl+"?q="+escape(getSearchInputObject().val());}}
var chatWin=window.open(chatUrl,"cchChatWin","width=560,height=650,scrollbars=no");chatWin.focus();var onChatWindowClosed=function(){var logParams=new Object();logParams.dataType="json";logParams.method="POST";logParams.url="/chat/lib/UILogHandler.aspx";logParams.data={lognumber:"CHA_105",level:"INFO",logentry:""};$.ajax(logParams);};var closeChatCheckInterval=500;var closeChatCheck=setInterval(function(){try{(chatWin==null||chatWin.closed)&&(clearInterval(closeChatCheck),onChatWindowClosed());}catch(ex){}},closeChatCheckInterval);}
function KbButtonClick(){var searchValue=getSearchInputObject().val();var a=window.location.href;if(a.toLowerCase().indexOf("/poc")>=0){window._KBlogger.LogInfo("KB_513",searchValue);}else{window._KBlogger.LogInfo("KB_177",searchValue);}
getSearchInputObject();if(getSearchInputObject().val()===""){window.displayWKAlert("Please enter a search term or question to search.");getSearchInputObject().toggleClass("darkText");getSearchInputObject().focus();return;}
document.kbSearchForm.searchText.value=searchValue;document.kbSearchForm.loadedSearchText.value=searchValue;document.kbSearchForm.action="/kb/home.aspx/search?q="+searchValue;document.kbSearchForm.submit();var logParams=new Object();logParams.dataType="json";logParams.method="POST";logParams.url="/chat/lib/UILogHandler.aspx";logParams.data={lognumber:"CHA_116",level:"INFO",logentry:searchValue};$.ajax(logParams);}
function qFocus(){var q=getSearchInputObject();if(q.hasClass("dimText")){q.val("");q.toggleClass("darkText");}}
function qBlur(){var q=getSearchInputObject();if(q.val()===""){q.toggleClass("dimText");}}
function qInitScript(){var q=getSearchInputObject();q.toggleClass("dimText");qBlur();q.focus();}
function runLuca(){var encryptParams=new Object();encryptParams.dataType="json";encryptParams.method="GET";encryptParams.url="/chat/ChatBotServices.aspx";encryptParams.success=function(request){if(request!=null){openChatBotWindow(request.url,request.data);}};$.ajax(encryptParams);}
function openChatBotWindow(url,data){var target="wkLuca";var chatWindow=window.open("",target,"width=800,height=800,scrollbars=no,location=no,menubar=no,status=no,titlebar=no,toolbar=no,resizable=yes");var container=chatWindow.document.createElement('div');var chatForm=chatWindow.document.createElement("form");chatForm.target=target;chatForm.method="post";chatForm.action=url;var chatInput=chatWindow.document.createElement("input");chatInput.type="text";chatInput.name="id";chatInput.value=data;chatInput.hidden=true;chatForm.appendChild(chatInput);container.appendChild(chatForm);chatWindow.document.body.appendChild(container);if(chatWindow){chatForm.submit();chatWindow.focus();window.ga("send","event","Chat Bot","start","Chat Page");window.ga("send","pageview",{'page':"/chat/chatbot.aspx"});}else{alert("You must allow popups for virtual assistant to work.");}
var onWindowClosed=function(){var logParams=new Object();logParams.dataType="json";logParams.method="POST";logParams.url="/chat/lib/UILogHandler.aspx";logParams.data={lognumber:"CHA_114",level:"INFO",logentry:""};$.ajax(logParams);};var closeChatBotCheckInterval=500;var closeChatBotCheck=setInterval(function(){try{(chatWindow==null||chatWindow.closed)&&(clearInterval(closeChatBotCheck),onWindowClosed());}catch(ex){}},closeChatBotCheckInterval);var logParams=new Object();logParams.dataType="json";logParams.method="POST";logParams.url="/chat/lib/UILogHandler.aspx";logParams.data={lognumber:"CHA_110",level:"INFO",logentry:""};$.ajax(logParams);}
function openSFSChatBotWindow(url,data,page){var target="wkLuca";var chatWindow=window.open("",target,"width=800,height=800,scrollbars=no,location=no,menubar=no,status=no,titlebar=no,toolbar=no,resizable=yes");var container=chatWindow.document.createElement('div');var chatForm=chatWindow.document.createElement("form");chatForm.target=target;chatForm.method="get";chatForm.action=url;container.appendChild(chatForm);chatWindow.document.body.appendChild(container);if(chatWindow){chatForm.submit();chatWindow.focus();if(page=="atxchat"){window.ga("send","event","SFS Chat Bot","start","ATX Chat Page");window.ga("send","pageview",{'page':"/atxchat"});}
else{window.ga("send","event","SFS Chat Bot","start","Taxwise Chat Page");window.ga("send","pageview",{'page':"/taxwisechat"});}}else{alert("You must allow popups for virtual assistant to work.");}
var onWindowClosed=function(page){var logParams=new Object();logParams.dataType="json";logParams.method="POST";logParams.url="/chat/lib/UILogHandler.aspx";if(page=="atxchat")
logParams.data={lognumber:"CHA_551",level:"INFO",logentry:""};else
logParams.data={lognumber:"CHA_553",level:"INFO",logentry:""};$.ajax(logParams);};var closeChatBotCheckInterval=500;var closeChatBotCheck=setInterval(function(){try{(chatWindow==null||chatWindow.closed)&&(clearInterval(closeChatBotCheck),onWindowClosed(page));}catch(ex){}},closeChatBotCheckInterval);var logParams=new Object();logParams.dataType="json";logParams.method="POST";logParams.url="/chat/lib/UILogHandler.aspx";if(page=="atxchat")
logParams.data={lognumber:"CHA_550",level:"INFO",logentry:""};else
logParams.data={lognumber:"CHA_552",level:"INFO",logentry:""};$.ajax(logParams);}
function lucaButtonClicked(){if(window.siAuthUser===""){window.loginSource="chatBot";window.loginTarget="/chat";var lf=new window.modalLoginForm();lf.display(runLuca);}else{runLuca();}}
function atxChatBotButtonClicked(url){openSFSChatBotWindow(url,"","atxchat");}
function taxwiseChatBotButtonClicked(url){openSFSChatBotWindow(url,"","taxwisechat");}
function getSearchInputObject(){return $(".ChatSearchWrapper #q");}
$(function(){$("#LucaButton").click(lucaButtonClicked);qInitScript();});