function modalLoginForm(){if(window[this.winId]){return window[this.winId];}
this.username=window.siAuthUser;window[this.winId]=this;}
modalLoginForm.prototype.winId="modalLoginForm1938";modalLoginForm.prototype.userNameId="LoginCtrl_txtEmail";modalLoginForm.prototype.passwordId="LoginCtrl_txtPassword";modalLoginForm.prototype.rememberId="LoginCtrl_chkRemember";modalLoginForm.prototype.LogInLogOutLink="loginlogout";modalLoginForm.prototype.RegisterNewUserLink="registerNewUser";modalLoginForm.prototype.wkEmailPattern=new RegExp("[^@]+@wolterskluwer\\.com","i");modalLoginForm.prototype.wkDomainPattern=new RegExp("^\s*na\\\\","i");modalLoginForm.prototype.callBack=null;modalLoginForm.prototype.initialize=function(){if(window.siAuthUser!=""){this.statusLoggedIn();}else{this.statusLoggedOut();}
this.setupSubmitForm();};var isRedirectionAllowed=function(url){var regex=RegExp('^[^\/]+\/[^\/].*$|^\/[^\/].*$');if(regex.test(url))
return true;else
{var returnURI=new URL(url);var whitelistedDomains=['https://(.*)[.]force[.]com$','https://(.*)[.]cch[.]com$'];for(var i=0;i<whitelistedDomains.length;i++){if(RegExp(whitelistedDomains[i]).test(returnURI.origin))
return true;}}
return false;}
modalLoginForm.prototype.loginSuccessResponse=function(rData){if($("success",rData).length>0){var success=$("success",rData).text();switch(success){case"mfaOption":{getUserName();getAccountsForUser(processAccountsAndContinue,true);if($("redirect",rData).length>0){location.href=unescape($("redirect",rData).text());}
break;}
case"pendingMfa":{if($("redirect",rData).length>0){location.href=unescape($("redirect",rData).text());}
break;}
case"true":{getUserName();getAccountsForUser(processAccountsAndContinue,true);var returnUrl=this.getQueryStringParams('ReturnUrl');if(returnUrl){var url=decodeURIComponent(returnUrl);if(isRedirectionAllowed(url))
window.location.href=url;else
window.location.href='/';}else if(!window.loginSource){location.reload();}
if(this.callBack!=null&&this.callBack!=""){this.callBack();}
break;}
default:{$("#loginModal").modal('hide');$("#"+this.passwordId).val("");if(!this.isInternalUser($("#"+this.userNameId).val())){displayWKAlert("You could not be logged in with those credentials.\nPlease try again.");}else{displayWKAlert("Please use your NA password to log in.");}
break;}}}else if($("redirect",rData).length>0){var url=unescape($("redirect",rData).text());location.href=url;}else{displayWKAlert("Login XML value not understood");location.href="/login/login.aspx";}};modalLoginForm.prototype.loginErrorResponse=function(rData){displayWKAlert("An error occurred trying to log in.  Please try again later.");};modalLoginForm.prototype.setupSubmitForm=function(){var loginForm=this;$("siLoginForm").submit(function(){return false;});$("#modalLoginSubmit").click(function(){var userName=document.getElementById(loginForm.userNameId).value;var password=document.getElementById(loginForm.passwordId).value;var rememberme=$("#"+loginForm.rememberId).is(':checked');this.username=userName;var errorList=new Array();if(userName===""){errorList.push("Email address is required.");}else{var emailPattern=/^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/
if(!emailPattern.test(userName)){errorList.push("Invalid email address.");}};if(password==="")errorList.push("Password is required.");if(errorList.length>0){$("#loginModal").modal("hide");displayWKAlert("Please correct the following:<br/>   *"+errorList.join("<br/>   *"),function(){$(".modal-content").width("290px");$("#loginModal").modal("show");});return false;};$.ajax({url:"/login/loginHandler.aspx",dataType:"xml",type:"POST",success:new Function("rData","window[\""+loginForm.winId+"\"].loginSuccessResponse(rData);"),error:new Function("rData","window[\""+loginForm.winId+"\"].loginErrorResponse(rData);"),data:{username:userName,password:password,rememberme:(rememberme?"true":"false")}});$("#loginModal").modal('hide');return false;});};modalLoginForm.prototype.display=function(callBack){if(callBack!=null||callBack!=""){this.callBack=callBack;}
$("body").css("cursor","default");$("#loginModal").modal();$("#loginModal").on('shown.bs.modal',function(){$("#loginModal #LoginCtrl_txtEmail").focus(function(){$("input").not("#txtProdSearch").unbind("keydown");$("#loginModal input").bind("keydown",function(event){var keycode=(event.keyCode?event.keyCode:(event.which?event.which:event.charCode));if(keycode==13){$("#modalLoginSubmit").click();return false;}else{return true;}});});$("#loginModal #LoginCtrl_txtPassword").focus(function(){$("input").not("#txtProdSearch").unbind("keydown");$("#loginModal input").bind("keydown",function(event){var keycode=(event.keyCode?event.keyCode:(event.which?event.which:event.charCode));if(keycode==13){$("#modalLoginSubmit").click();return false;}else{return true;}});});if($("#loginModal #LoginCtrl_txtEmail").length>0){if($("#loginModal #LoginCtrl_txtEmail").val().length>0){$("#loginModal #LoginCtrl_txtPassword").focus();}
else{$("#loginModal #LoginCtrl_txtEmail").focus();}}});}
modalLoginForm.prototype.getEmailGuid=function(){var cookies=new siCookieParser(document.cookie);if(cookies.getValue("wkssrm")){$.ajax({url:"/login/loginHandler.aspx",dataType:"xml",type:"POST",success:new Function("rData",this.buildWindowCall("emailGuidTranslation")+"(rData);"),data:{rememberEmailGuid:cookies.getValue("wkssrm")}});}};modalLoginForm.prototype.emailGuidTranslation=function(rData){var email=$("email",rData).text();$("#"+this.userNameId).val(email);if(email!=""){$("#"+this.rememberId).attr("checked",true);}}
modalLoginForm.prototype.buildWindowCall=function(funcName){return"window[\""+this.winId+"\"]."+funcName;};modalLoginForm.prototype.showLoginForm=function(){this.callBack=null;this.statusLoggedOut();this.getEmailGuid();$("#loginModal").on('shown.bs.modal',function(){$("#loginModal #LoginCtrl_txtEmail").focus(function(){$("input").not("#txtProdSearch").unbind("keydown");$("#loginModal input").bind("keydown",function(event){var keycode=(event.keyCode?event.keyCode:(event.which?event.which:event.charCode));if(keycode==13){$("#modalLoginSubmit").click();return false;}else{return true;}});});$("#loginModal #LoginCtrl_txtPassword").focus(function(){$("input").not("#txtProdSearch").unbind("keydown");$("#loginModal input").bind("keydown",function(event){var keycode=(event.keyCode?event.keyCode:(event.which?event.which:event.charCode));if(keycode==13){$("#modalLoginSubmit").click();return false;}else{return true;}});});if($("#loginModal #LoginCtrl_txtEmail").val().length>0){$("#loginModal #LoginCtrl_txtPassword").focus();}
else{$("#loginModal #LoginCtrl_txtEmail").focus();}});$("#loginModal").modal();};modalLoginForm.prototype.hideLoginForm=function(){$("#loginModal").fadeOut("slow");this.statusLoggedOut();};modalLoginForm.prototype.statusLoggedOut=function(){$("#"+this.LogInLogOutLink).unbind("click").click(new Function("event","event.preventDefault();"+this.buildWindowCall("showLoginForm")+"();")).html("Log In");$("#"+this.RegisterNewUserLink).show();};modalLoginForm.prototype.statusLoginFormDisplay=function(){$("#"+this.LogInLogOutLink).unbind("click").click(new Function("event","event.preventDefault();"+this.buildWindowCall("hideLoginForm")+"();"));};modalLoginForm.prototype.statusLoggedIn=function(){var welcomeText="Welcome";if(this.username!=""){welcomeText=welcomeText+" "+this.username.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}
$("#"+this.LogInLogOutLink).unbind("click").click(new Function("event","event.preventDefault();window[\""+this.winId+"\"].logout();")).html("Log Out");$("#"+this.RegisterNewUserLink).hide();};modalLoginForm.prototype.logout=function(){displayWKConfirm("Are you sure that you wish to log out?",completeLogOut,1);};modalLoginForm.prototype.isInternalUser=function(user){return this.wkEmailPattern.test(user)||this.wkDomainPattern.test(user)};modalLoginForm.prototype.getQueryStringParams=function(sParam){{var sPageURL=window.location.search.substring(1);var sURLVariables=sPageURL.split('&');for(var i=0;i<sURLVariables.length;i++){var sParameterName=sURLVariables[i].split('=');if(sParameterName[0]==sParam){return sParameterName[1];}}}}
$(document).ready(function(){var lf=new modalLoginForm();lf.initialize();});